<?php
/**
 * Mailjet
 */

function mj_customsmtp_help($path, $arg) {
  switch ($path) {
    case 'admin/help#mj_customsmtp':
      return t('Send your emails by your Mailjet API.');
  }
}

function mj_customsmtp_menu() {
  $items['admin/config/system/mj_customsmtp'] = array(
    'title'            => 'Mailjet settings',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('mj_customsmtp_admin_settings'),
    'access arguments' => array('administer mj_customsmtp module'),
    'description'      => 'Send your emails by your Mailjet API.',
    'file'             => 'mj_customsmtp.admin.inc',
  );
  return $items;
}

function mj_customsmtp_permission() {
  return array(
    'administer mj_customsmtp module' => array(
      'title' => t('Administer Mailjet settings module'),
      'description' => t('Perform administration tasks for Mailjet settings module.'))
  );
}

function mj_customsmtp_mail($key, &$message, $params) {
  if ($key == 'mj_customsmtp-test') {
    $message['subject'] = $params['subject'];
    $message['body']    = $params['body'];
  }
}
